"use client";

import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { Icon } from "@iconify/react";
import { apiExportCase } from "../../../../lib/api/export-case";
import { apiPricing } from "../../../../lib/api/pricing";
import { apiCosting } from "../../../../lib/api/costing";
import { apiFinancial } from "../../../../lib/api/financial";
import { apiRisk } from "../../../../lib/api/risk";
import { apiAdvisor } from "../../../../lib/api/advisor";
import { apiDocuments } from "../../../../lib/api/documents";
import { CaseSubNav } from "../../../../components/export-case/CaseSubNav";
import { CaseProgressStepper } from "../../../../components/export-case/CaseProgressStepper";
import { ViewOnlyBanner } from "../../../../components/export-case/ViewOnlyBanner";
import { StageNotReadyState } from "../../../../components/export-case/StageNotReadyState";
import { ConfirmRegenerateModal } from "../../../../components/export-case/ConfirmRegenerateModal";
import { AIAdvisorWorkspace } from "../../../../components/export-case/AIAdvisorWorkspace";
import { CostingReadOnlyView } from "../../../../components/export-case/CostingReadOnlyView";
import { FinancialAnalysis } from "../../../../components/export-case/FinancialAnalysis";
import { notificationStore } from "../../../../lib/services/notificationStore";

import { Button } from "../../../../components/ui/button";
import { toast } from "sonner";
import { useUserProfile } from "../../../../hooks/useUserProfile";

import { PdfPreviewModal } from "../../../../components/ui/pdf-preview-modal";
import { downloadDocument } from "../../../../lib/utils/pdf-downloader";

export default function ExportCaseDetailPage() {
  const params = useParams();
  const router = useRouter();
  const searchParams = useSearchParams();
  const queryClient = useQueryClient();
  const { profile } = useUserProfile();
  const caseId = params.caseId as string;
  const currentTab = searchParams.get("tab") || "overview";

  const [confirmRegenerateOpen, setConfirmRegenerateOpen] = useState(false);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const [previewModal, setPreviewModal] = useState<{ open: boolean; documentId: string; filename: string }>({
    open: false,
    documentId: "",
    filename: "",
  });

  const canDelete = profile?.role === "export_manager" || profile?.role === "admin";

  const handleTabChange = (tabId: string) => {
    router.push(`/em-export-case/${caseId}?tab=${tabId}`);
  };


  const { data: caseData, isLoading } = useQuery({
    queryKey: ["export-case", caseId],
    queryFn: () => apiExportCase.get(caseId),
  });

  const { data: costData } = useQuery({
    queryKey: ["costing", caseId],
    queryFn: () => apiCosting.getCostData(caseId),
    retry: false,
  });

  const { data: pricingData } = useQuery({
    queryKey: ["pricing", caseId],
    queryFn: () => apiPricing.getPricing(caseId),
    retry: false,
  });

  const { data: financialData } = useQuery({
    queryKey: ["financial", caseId],
    queryFn: () => apiFinancial.getAnalysis(caseId),
    retry: false,
  });

  const { data: riskData } = useQuery({
    queryKey: ["risk", caseId],
    queryFn: () => apiRisk.getRiskAssessment(caseId),
    retry: false,
  });

  const { data: advisorData, refetch: refetchAdvisor } = useQuery({
    queryKey: ["advisor", caseId],
    queryFn: () => apiAdvisor.getRecommendation(caseId),
    retry: false,
  });

  const deleteMutation = useMutation({
    mutationFn: () => apiExportCase.delete(caseId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["export-cases"] });
      router.push("/em-export-case");
    },
  });

  const regenerateAdvisorMutation = useMutation({
    mutationFn: () => apiAdvisor.generateRecommendation(caseId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["advisor", caseId] });
      refetchAdvisor();
      setConfirmRegenerateOpen(false);
      toast.success("AI Recommendation successfully regenerated!");
      if (exportCase) {
        notificationStore.addNotification({
          caseId,
          caseName: exportCase.name,
          message: "AI Advisor recommendation regenerated by Export Manager. Ready for executive review.",
          targetRole: "company_owner",
          targetTab: "overview",
        });
      }
    },
    onError: (err: any) => {
      toast.error(err.message || "Failed to generate AI recommendation.");
    },
  });

  const handleGeneratePdf = async (type: "quotation" | "proforma") => {
    setIsGeneratingPdf(true);
    try {
      const res = type === "quotation"
        ? await apiDocuments.generateQuotation(caseId)
        : await apiDocuments.generateProformaInvoice(caseId);
      
      if (res?.success) {
        toast.success(`${type.toUpperCase()} PDF document generated successfully!`);
        const doc = res.data;
        if (doc?.documentId && doc?.filename) {
          setTimeout(() => setPreviewModal({ open: true, documentId: doc.documentId, filename: doc.filename }), 300);
        }
        if (exportCase) {
          notificationStore.addNotification({
            caseId,
            caseName: exportCase.name,
            message: `${type.toUpperCase()} PDF commercial document issued by Export Manager. Available for executive download.`,
            targetRole: "company_owner",
            targetTab: "documents",
          });
        }
      } else {
        toast.error("Failed to generate PDF document.");
      }
    } catch (err: any) {
      toast.error(err.message || "Failed to generate PDF document.");
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  if (isLoading) {
    return <div className="p-8 flex justify-center"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-[#00A651]"></div></div>;
  }

  const exportCase = caseData?.data;
  const costing = costData?.data;
  const pricing = pricingData?.data?.pricing;
  const financial = financialData?.data?.analysis;
  const risk = riskData?.data?.assessment;
  const recommendation = advisorData?.data?.recommendation;

  if (!exportCase) {
    return (
      <div className="p-8 text-center space-y-4">
        <p className="text-red-500 font-bold">Failed to load export case details.</p>
        <Link href="/em-export-case">
          <Button variant="outline">Back to List</Button>
        </Link>
      </div>
    );
  }

  const feasPct = exportCase.feasibilityScore != null ? exportCase.feasibilityScore * 10 : null;
  const feasLabel = feasPct == null ? "—" : feasPct >= 80 ? "High" : feasPct >= 60 ? "Moderate" : "Low";
  const feasColor = feasPct == null ? "text-gray-400" : feasPct >= 80 ? "text-emerald-700" : feasPct >= 60 ? "text-amber-700" : "text-rose-700";

  return (
    <div className="space-y-6">

      {/* TAB CONTENT: Overview */}
      {currentTab === "overview" && (
        <div className="space-y-6">
          <CaseProgressStepper
            hasCostData={!!costing}
            hasPricingData={!!pricing}
            hasFinancialData={!!financial}
            hasRiskData={!!risk}
            hasAdvisorData={!!recommendation}
          />

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="bg-white rounded-3xl border border-[#E8E3D9] p-5 shadow-sm">
              <p className="text-[10px] font-bold text-[#9CA3AF] uppercase">Product</p>
              <p className="text-base font-black text-[#1F2937]">{exportCase.product || "—"}</p>
            </div>
            <div className="bg-white rounded-3xl border border-[#E8E3D9] p-5 shadow-sm">
              <p className="text-[10px] font-bold text-[#9CA3AF] uppercase">Destination</p>
              <p className="text-base font-black text-[#1F2937]">{exportCase.destinationCountry}</p>
            </div>
            <div className="bg-white rounded-3xl border border-[#E8E3D9] p-5 shadow-sm">
              <p className="text-[10px] font-bold text-[#9CA3AF] uppercase">Feasibility Score</p>
              <p className={`text-base font-black ${feasColor}`}>
                {feasPct != null ? `${feasLabel} (${feasPct.toFixed(0)}/100)` : "Not analyzed yet"}
              </p>
            </div>
          </div>
        </div>
      )}

      {/* TAB CONTENT: Cost */}
      {currentTab === "cost" && (
        <div className="space-y-4">
          <ViewOnlyBanner ownerRoleName="Finance Staff" dataTopic="Export Costing Components" />
          {!costing ? (
            <StageNotReadyState
              currentStage="Export Costing Data"
              prerequisiteStage="Export Cost Input Form"
              responsibleRole="Finance Staff"
            />
          ) : (
            <CostingReadOnlyView cost={costing} />
          )}
        </div>
      )}

      {/* TAB CONTENT: Pricing */}
      {currentTab === "pricing" && (
        <div className="space-y-4">
          {!costing ? (
            <StageNotReadyState
              currentStage="Pricing & Incoterms Simulation"
              prerequisiteStage="Costing Data Input"
              responsibleRole="Finance Staff"
              message="Waiting for Finance Staff to complete costing input before Pricing can be calculated."
            />
          ) : (
            <div className="bg-white rounded-3xl border border-[#E8E3D9] p-6 shadow-sm space-y-5">
              <div className="flex items-center justify-between">
                <h4 className="text-lg font-extrabold text-[#1F2937]">Pricing Engine & Incoterms Execution</h4>
                <Link href={`/em-export-case/${caseId}/pricing`} className="px-4 py-2 bg-[#00A651] text-white text-xs font-bold rounded-xl shadow-md">
                  Open Pricing Calculator
                </Link>
              </div>
              <p className="text-xs text-[#6B7280]">
                As Export Manager, you have full authority to determine export pricing strategies based on Incoterms (EXW, FOB, CFR, CIF) and target profit margins.
              </p>
            </div>
          )}
        </div>
      )}

      {/* TAB CONTENT: Scenario */}
      {currentTab === "scenario" && (
        <div className="space-y-4">
          <div className="bg-white rounded-3xl border border-[#E8E3D9] p-6 shadow-sm space-y-5">
            <div className="flex items-center justify-between">
              <h4 className="text-lg font-extrabold text-[#1F2937]">Transaction Scenario Simulation</h4>
              <Link href={`/em-export-case/${caseId}/scenario`} className="px-4 py-2 bg-[#00A651] text-white text-xs font-bold rounded-xl shadow-md">
                Open Scenario Simulation
              </Link>
            </div>
            <p className="text-xs text-[#6B7280]">
              Compare pricing alternatives, freight cost variations, and profit margins under varying market conditions.
            </p>
          </div>
        </div>
      )}

      {/* TAB CONTENT: Financial Analysis */}
      {currentTab === "financial" && (
        <FinancialAnalysis caseId={caseId} hideBackButton />
      )}

      {/* TAB CONTENT: Risk */}
      {currentTab === "risk" && (
        <div className="space-y-4">
          <div className="bg-[#FFFFFF] rounded-3xl border border-[#E8E3D9] p-6 shadow-sm space-y-5">
            <div className="flex items-center justify-between">
              <h4 className="text-lg font-extrabold text-[#1F2937]">Country & Payment Risk Assessment</h4>
              <Link href={`/em-export-case/${caseId}/risk`} className="px-4 py-2 bg-[#00A651] text-white text-xs font-bold rounded-xl shadow-md">
                Manage Risk Assessment
              </Link>
            </div>
            <p className="text-xs text-[#6B7280]">
              Evaluate destination country political/economic risk levels and select secure payment methods (L/C, T/T, Advance Deposit).
            </p>
          </div>
        </div>
      )}

      {/* TAB CONTENT: Advisor */}
      {currentTab === "advisor" && (
        <AIAdvisorWorkspace caseId={caseId} />
      )}


      {/* TAB CONTENT: Documents */}
      {currentTab === "documents" && (
        <div className="bg-white rounded-3xl border border-[#E8E3D9] p-6 shadow-sm space-y-5">
          <h4 className="text-lg font-extrabold text-[#1F2937]">Commercial Document Generation</h4>
          <p className="text-xs text-[#6B7280]">
            As Export Manager, you are authorized to issue official commercial export documents for buyers:
          </p>
          <div className="flex items-center gap-3 pt-2">
            <Button
              onClick={() => handleGeneratePdf("quotation")}
              disabled={isGeneratingPdf}
              className="bg-[#00A651] hover:bg-[#008F44] text-white font-bold text-xs h-10 px-5 rounded-xl shadow-md"
            >
              Generate Quotation (PDF)
            </Button>
            <Button
              onClick={() => handleGeneratePdf("proforma")}
              disabled={isGeneratingPdf}
              className="bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs h-10 px-5 rounded-xl shadow-md"
            >
              Generate Proforma Invoice (PDF)
            </Button>
          </div>
        </div>
      )}
      <PdfPreviewModal
        open={previewModal.open}
        onClose={() => setPreviewModal((s) => ({ ...s, open: false }))}
        documentId={previewModal.documentId}
        filename={previewModal.filename}
      />
    </div>
  );
}
