"use client";

import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import Link from "next/link";
import { apiFinancial } from "../../lib/api/financial";
import { Button } from "../ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "../ui/card";
import { Alert, AlertTitle, AlertDescription } from "../ui/alert";
import { useUserProfile } from "../../hooks/useUserProfile";
import { Label } from "../ui/label";

interface FinancialAnalysisProps {
  caseId: string;
  backUrl: string;
}

export function FinancialAnalysis({ caseId, backUrl }: FinancialAnalysisProps) {
  const queryClient = useQueryClient();
  const { profile } = useUserProfile();
  
  const [selectedIncoterm, setSelectedIncoterm] = useState<"EXW" | "FOB" | "CFR" | "CIF">("FOB");
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const canRecalculate = profile?.role === "finance_staff" || profile?.role === "admin" || profile?.role === "export_manager";

  const { data, isLoading, error } = useQuery({
    queryKey: ["financial-analysis", caseId],
    queryFn: () => apiFinancial.getAnalysis(caseId),
  });

  const mutation = useMutation({
    mutationFn: () => apiFinancial.recalculateAnalysis(caseId, { incoterm: selectedIncoterm }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["financial-analysis", caseId] });
      setErrorMsg(null);
    },
    onError: (err: any) => {
      setErrorMsg(err.message || "Failed to recalculate financial analysis.");
    }
  });

  if (isLoading) {
    return <div className="p-8 flex justify-center"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900"></div></div>;
  }

  if (error) {
    return (
      <div className="space-y-6 max-w-4xl mx-auto">
        <Link href={backUrl} className="text-sm text-blue-500 hover:underline mb-2 block">
          &larr; Back
        </Link>
        <Alert variant="destructive">
          <AlertTitle>Analysis Unavailable</AlertTitle>
          <AlertDescription>
            The financial analysis could not be loaded. Please ensure that the Cost Data and Pricing modules have been completed first.
          </AlertDescription>
        </Alert>
      </div>
    );
  }

  const analysis = data?.data?.analysis;

  if (!analysis) {
    return <div className="p-8 text-center text-gray-500">No data available.</div>;
  }

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <div>
        <Link href={backUrl} className="text-sm text-blue-500 hover:underline mb-2 block">
          &larr; Back
        </Link>
        <h2 className="text-3xl font-bold tracking-tight">Financial Analysis</h2>
        <p className="text-gray-500 mt-1">Review profitability margins and break-even points generated by the system.</p>
      </div>

      <div className="grid md:grid-cols-3 gap-6">
        <div className="md:col-span-2 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Generated Financial Metrics</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="grid grid-cols-2 gap-6">
                <div>
                  <p className="text-sm text-gray-500 font-medium mb-1">Revenue (IDR)</p>
                  <p className="text-2xl font-bold text-green-700">Rp {(analysis.revenueIDR || 0).toLocaleString()}</p>
                </div>
                <div>
                  <p className="text-sm text-gray-500 font-medium mb-1">Gross Profit (IDR)</p>
                  <p className="text-2xl font-bold text-blue-700">Rp {(analysis.grossProfitIDR || 0).toLocaleString()}</p>
                </div>
                <div>
                  <p className="text-sm text-gray-500 font-medium mb-1">Profit Margin (%)</p>
                  <p className="text-2xl font-bold text-indigo-700">{(analysis.profitMarginPct || 0).toFixed(2)}%</p>
                </div>
                <div>
                  <p className="text-sm text-gray-500 font-medium mb-1">Return on Investment (ROI)</p>
                  <p className="text-2xl font-bold text-purple-700">{(analysis.roiPct || 0).toFixed(2)}%</p>
                </div>
                <div className="col-span-2">
                  <p className="text-sm text-gray-500 font-medium mb-1">Break Even Point (Quantity)</p>
                  <p className="text-2xl font-bold text-slate-800">{Math.ceil(analysis.breakEvenQty || 0).toLocaleString()} units</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Base Cost & Pricing Factors</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex justify-between border-b pb-2">
                <span className="text-gray-600">Total Base Cost (IDR)</span>
                <span className="font-semibold">Rp {(analysis.totalCostIDR || 0).toLocaleString()}</span>
              </div>
              <div className="flex justify-between border-b pb-2">
                <span className="text-gray-600">Calculated Selling Price (IDR)</span>
                <span className="font-semibold">Rp {(analysis.sellingPriceIDR || 0).toLocaleString()}</span>
              </div>
              <div className="flex justify-between pb-2">
                <span className="text-gray-600">Sales Quantity</span>
                <span className="font-semibold">{(analysis.quantity || 0).toLocaleString()} units</span>
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="space-y-6">
          <Card className="border-blue-200">
            <CardHeader className="bg-blue-50 border-b border-blue-100">
              <CardTitle className="text-blue-900">Recalculate Analysis</CardTitle>
            </CardHeader>
            <CardContent className="pt-6 space-y-4">
              {errorMsg && (
                <div className="p-3 text-sm bg-red-50 text-red-500 rounded-md">
                  {errorMsg}
                </div>
              )}
              
              <div className="space-y-2">
                <Label htmlFor="incoterm">Simulate with Incoterm</Label>
                <select
                  id="incoterm"
                  className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                  value={selectedIncoterm}
                  onChange={(e) => setSelectedIncoterm(e.target.value as "EXW" | "FOB" | "CFR" | "CIF")}
                  disabled={!canRecalculate || mutation.isPending}
                >
                  <option value="EXW">EXW (Ex Works)</option>
                  <option value="FOB">FOB (Free on Board)</option>
                  <option value="CFR">CFR (Cost and Freight)</option>
                  <option value="CIF">CIF (Cost, Insurance, and Freight)</option>
                </select>
                <p className="text-xs text-gray-500">
                  Currently active: <span className="font-semibold">{analysis.selectedIncoterm}</span>
                </p>
              </div>
            </CardContent>
            <CardFooter>
              <Button 
                className="w-full" 
                onClick={() => mutation.mutate()}
                disabled={!canRecalculate || mutation.isPending || selectedIncoterm === analysis.selectedIncoterm}
              >
                {mutation.isPending ? "Recalculating..." : "Recalculate Metrics"}
              </Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    </div>
  );
}
